name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy: # nombre del job, puede ser cualquiera
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # solo trae el ultimo commit
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      # - name: Lint
      #   run: npm run eslint
      # - name: Build app
      #   run: npm run build